FELIX-2492 : scr plugin: using src annotations causes NoClassDefFoundError and other errors
git-svn-id: https://svn.apache.org/repos/asf/felix/trunk/scrplugin/generator@1132934 13f79535-47bb-0310-9956-ffa450edef68