FELIX-2122 Prevent NullPointerException if NoClassDefFoundError does not provide a message
git-svn-id: https://svn.apache.org/repos/asf/felix/trunk@915246 13f79535-47bb-0310-9956-ffa450edef68